runtime: php
env: flex

runtime_config: document_root: public

#ensure we skip ".env", which is only for local environment
skip_files:
        - .env

automatic_scaling:
	min_num_instances: 1
	max_num_instances: 1

resources:
	cpu: 2
	memory_gb: 4
	disk_size_gb: 100

env_variables:
	#put production environment variables here.
	APP_DEBUG: true
	APP_ENV: production
	APP_KEY: 9aqBiDM183GxVMYY//qwTLQrAiurnBuvhk+TxuZrWNQ=
	APP_NAME: "GCP App - CODE"

	LOG_LEVEL: debug
